### PR TITLE
fix: unlisten "abort" event on offListener

### LINKED ISSUE #8: Maybe a redundant code
It seems like there is some incorrectness in the code of `onAbort` function (at [src/events-to-async.ts:119](https://github.com/azu/events-to-async/blob/main/src/events-to-async.ts#L119)). It removes `offListener` from the `abort` event listeners. But there is no corresponding `addEventListener` call with `offListener` as an argument.

### PR DESCRIPTION
**Pull request by azu**
It was missing that removeEventListner for `abort` event on abortSignal.

- fix #8

### CODE REVIEW

File: src/events-to-async.ts [hunk 1]
```diff
@@ -42,13 +42,13 @@ export function on<R extends [...any]>(
...
-    const offListener = () => {
-        unHandle?.();
-    };
     const onAbort = () => {
-        abortSignal?.removeEventListener("abort", offListener);
         error = new Error("Abort Error");
     };
+    const offListener = () => {
+        unHandle?.();
+        abortSignal?.removeEventListener("abort", onAbort);
```
Comment (azu) [inline src/events-to-async.ts:50]: <-> `abortSignal?.addEventListener("abort", onAbort, { once: true });`
